name: simplytoast
base: core22
version: '0.9.4.5'
summary: Startup application manager for Linux
description: |
  SimplyToast lets you manage startup apps, background processes,
  and autostart entries with a clean GTK UI.

grade: stable
confinement: strict

apps:
  simplytoast:
    command: usr/bin/simplytoast
    desktop: usr/share/applications/com.toast1599.SimplyToast.desktop

parts:
  simplytoast:
    plugin: dump
    source: .
    organize:
      src/main.py: usr/bin/simplytoast
      data: usr/share/simplytoast/data
      assets: usr/share/simplytoast/assets
      data/com.toast1599.SimplyToast.desktop: usr/share/applications/com.toast1599.SimplyToast.desktop
      data/com.toast1599.SimplyToast.png: usr/share/icons/hicolor/512x512/apps/com.toast1599.SimplyToast.png
